Monit 26299 golang-otel-example
wavefrontHQ/opentelemetry-examples pull request #24
Opened 2021-12-23 17:07 UTC by deosu

2022-01-03 21:03 UTC, thepeterstone requested changes
A few minor changes and typos - otherwise LGTM!

2022-01-03 21:03 UTC, thepeterstone commented on golang-example/main.go
> +	ctx := context.Background()
Might be tidier to do 
```
ctx, cancel := context.WithCancel(context.Background())
```
and call `cancel` in the shutdown function.

2022-01-03 21:27 UTC, deosu commented on .github/workflows/main.yml
> +          WAIT_TIME=20
Ideally, 15 seconds should be enough, but sometimes I have noticed it takes more than that. As we have added more jobs that run in parallel, I thought it is better to give 5 seconds more to finish a job.

2022-01-03 21:30 UTC, deosu commented on .gitignore
> -*.mod
Sure, I'll add that.

2022-01-03 21:31 UTC, deosu commented on go-example/auto-instrumentation/README.md
> +in [`mod.go`](https://github.com/wavefrontHQ/opentelemetry-examples/blob/master/go-example/go.mod). To install
Resolved.

2022-01-03 21:31 UTC, deosu commented on go-example/auto-instrumentation/README.md
> +in [`mod.go`](https://github.com/wavefrontHQ/opentelemetry-examples/blob/master/go-example/go.mod). To install
Resolved.

2022-01-03 21:36 UTC, deosu commented on go-example/auto-instrumentation/main.go
> +		log.Printf("Could not set resources: ", err)
It should be Fatal, we can not continue without resources.

2022-01-03 21:38 UTC, deosu commented on go-example/manual-instrumentation/README.md
> +in [`mod.go`](https://github.com/wavefrontHQ/opentelemetry-examples/blob/master/go-example/go.mod).
Resolved.

2022-01-03 21:48 UTC, deosu commented on go-example/manual-instrumentation/main.go
> +		log.Printf("%s: %v", message, err)
agree, fixed.

2022-01-04 20:52 UTC, deosu commented
@thepeterstone can you please review again and approve?

2022-01-05 00:00 UTC, thepeterstone approved these changes

2022-01-05 00:30 UTC, merged